services:
  - type: web
    name: telegram-file-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir
    startCommand: python file_downloader_bot.py
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
